name: Run nanDECK and Upload Export

on:
  push

jobs:
  build-nandeck:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Export characters
      run: |
        .\nandeck\nanDECK.exe .\nandeck\decks\cards.txt /exec
      shell: cmd

    - name: Export main deck
      run: |
        .\nandeck\nanDECK.exe .\nandeck\decks\characters.txt /exec
      shell: cmd
      
    - name: Upload Export Folder
      uses: actions/upload-artifact@v4
      with:
        name: nandeck-export
        path: nandeck/export
        retention-days: 1
